export const journeyTestIds = {
  battle: 'journey-battle',
  battleBack: 'journey-battle-back',
  duelHeadline: 'journey-duel-headline',
  duelPhase: 'journey-duel-phase',
  entryTier: 'journey-entry-tier',
  error: 'journey-error',
  lobby: 'journey-lobby',
  mode: {
    direct: 'journey-mode-direct',
    house: 'journey-mode-house',
    matchmaking: 'journey-mode-matchmaking',
  },
  opponentWallet: 'journey-opponent-wallet',
  persistedDuel: 'journey-persisted-duel',
  persistedDuelCancel: 'journey-persisted-duel-cancel',
  persistedDuelContinue: 'journey-persisted-duel-continue',
  persistedDuelCopy: 'journey-persisted-duel-copy',
  persistedDuelFund: 'journey-persisted-duel-fund',
  persistedDuelHouse: 'journey-persisted-duel-house',
  persistedDuelRestart: 'journey-persisted-duel-restart',
  primaryAction: 'journey-primary-action',
  pull: {
    opponent: 'journey-pull-opponent',
    you: 'journey-pull-you',
  },
  pullName: {
    opponent: 'journey-pull-name-opponent',
    you: 'journey-pull-name-you',
  },
  pullValue: {
    opponent: 'journey-pull-value-opponent',
    you: 'journey-pull-value-you',
  },
  provider: {
    opponent: 'journey-provider-opponent',
    you: 'journey-provider-you',
  },
  resultMargin: 'journey-result-margin',
  resultRematch: 'journey-result-rematch',
  resultShare: 'journey-result-share',
  resultTotalValue: 'journey-result-total-value',
  settlementReference: 'journey-settlement-reference',
  tier: (value: number) => `journey-tier-${value}`,
  walletAuthenticationPrepare: 'journey-wallet-auth-prepare',
  walletAuthenticationSign: 'journey-wallet-auth-sign',
  walletDialog: 'journey-wallet-dialog',
  walletDisconnect: 'journey-wallet-disconnect',
  walletMenu: 'journey-wallet-menu',
  walletOption: 'journey-wallet-option',
  winner: {
    opponent: 'journey-winner-opponent',
    you: 'journey-winner-you',
  },
} as const;
